logLevel = "INFO"
defaultEntryPoints = ["http"]

[accessLog]

[entryPoints]
[entryPoints.http]
address = ":80"
compress = true

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
