FROM node:12.16.1-alpine as builder

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./package.json /usr/src/app/

RUN apk --no-cache --virtual build-dependencies add git python make g++ \
    && npm i \
    && npm cache clean --force \
    && apk del build-dependencies

COPY . /usr/src/app

ARG GENERATE_SOURCEMAP
ENV GENERATE_SOURCEMAP=false

RUN npm run build
RUN rm -r Dockerfile Dockerfile-prod src package-lock.json

FROM nginx:stable-alpine
COPY --from=builder /usr/src/app/build/ /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/conf.d/default.conf